"""create_export_artifacts_table

Revision ID: 08ea54a45112
Revises: f8a921179c03
Create Date: 2026-06-06 14:02:49.858373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ea54a45112'
down_revision: Union[str, None] = 'f8a921179c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_artifacts_project_id'), 'export_artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_artifacts_project_id'), table_name='export_artifacts')
    op.drop_table('export_artifacts')
    # ### end Alembic commands ###
