"""add_mlops_tables

Revision ID: 6f1a4e5d6c8b
Revises: 7a0d45f1b2c4
Create Date: 2026-06-08 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1a4e5d6c8b'
down_revision: Union[str, None] = '7a0d45f1b2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)

    # Modify training_runs to add MLOps lineage columns
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experiment_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('dataset_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('dataset_version_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_training_runs_experiments', 'experiments', ['experiment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_training_runs_datasets', 'datasets', ['dataset_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_training_runs_dataset_versions', 'dataset_versions', ['dataset_version_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_training_runs_experiment_id', ['experiment_id'], unique=False)
        batch_op.create_index('ix_training_runs_dataset_id', ['dataset_id'], unique=False)
        batch_op.create_index('ix_training_runs_dataset_version_id', ['dataset_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_training_runs_dataset_version_id')
        batch_op.drop_index('ix_training_runs_dataset_id')
        batch_op.drop_index('ix_training_runs_experiment_id')
        batch_op.drop_constraint('fk_training_runs_dataset_versions', type_='foreignkey')
        batch_op.drop_constraint('fk_training_runs_datasets', type_='foreignkey')
        batch_op.drop_constraint('fk_training_runs_experiments', type_='foreignkey')
        batch_op.drop_column('dataset_version_id')
        batch_op.drop_column('dataset_id')
        batch_op.drop_column('experiment_id')

    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')

    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
