"""add_phase4_models

Revision ID: 7a0d45f1b2c4
Revises: 08ea54a45112
Create Date: 2026-06-08 16:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0d45f1b2c4'
down_revision: Union[str, None] = '08ea54a45112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('training_run_id', sa.Uuid(), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_artifacts_project_id'), 'model_artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_model_artifacts_training_run_id'), 'model_artifacts', ['training_run_id'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('model_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_artifact_id'], ['model_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployments_model_artifact_id'), 'deployments', ['model_artifact_id'], unique=False)

    op.create_table('deployment_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Float(), nullable=False),
    sa.Column('gpu_usage_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_metrics_deployment_id'), 'deployment_metrics', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_metrics_timestamp'), 'deployment_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_metrics_timestamp'), table_name='deployment_metrics')
    op.drop_index(op.f('ix_deployment_metrics_deployment_id'), table_name='deployment_metrics')
    op.drop_table('deployment_metrics')

    op.drop_index(op.f('ix_deployments_model_artifact_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_table('deployments')

    op.drop_index(op.f('ix_model_artifacts_training_run_id'), table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_project_id'), table_name='model_artifacts')
    op.drop_table('model_artifacts')
    # ### end Alembic commands ###
