"""add celery_task_id to training_jobs

Revision ID: e5aa17bef163
Revises: 3cca460124dd
Create Date: 2026-06-03 16:17:18.441136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5aa17bef163'
down_revision: Union[str, None] = '3cca460124dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_jobs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_jobs', 'celery_task_id')
    # ### end Alembic commands ###
